services:
  web:
    build: .
    command: /app/start.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DEBUG=False
      - DJANGO_READ_DOT_ENV_FILE=False
      - DJANGO_SECRET_KEY=django-insecure-bpc6^x424*ilkrqmc3w5xyz#go+m44*@v7ebe0$ip@b7@ls0lr
      - DJANGO_DATABASE_URL=postgres://postgres:postgres@db:5432/task
    depends_on:
      - db
      - redis
      - celery

  db:
    image: postgres
    environment:
      POSTGRES_DB: task
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis_broker
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A config worker --loglevel=info
    depends_on:
      - redis
      - db
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    volumes:
      - .:/app

volumes:
  postgres_data:
